sudo: required
services:
  - docker

before_install:
  - docker build -t alexismayfire/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexismayfire/docker-react npm run test -- --coverage
